site_name: aimet-ml
site_url: https://aimet-tech.github.io/aimet-ml
repo_url: https://github.com/aimet-tech/aimet-ml
repo_name: aimet-tech/aimet-ml
#strict: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules:
    - features: api/features.md
    - metrics: api/metrics.md
    - model_selection: api/model_selection.md
    - processing: api/processing.md
    - utils: api/utils.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
      watch:
        - aimet_ml
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://web.facebook.com/aimet.tech
      name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/aimet-tech/aimet-ml
      name: Github
    - icon: material/email
      link: "mailto:pasit.j@aimet.tech"
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
